### ISSUE TITLE
Full dataset release [List Functions]

### ISSUE THREAD

**Issue by gsoykan** [linlu-qiu/lm-inductive-reasoning#1]
Thank you for your valuable contributions. I've been eager to examine the datasets in your repository. However, upon inspection of the data folder, I noticed that the datasets, particularly the 'list functions' dataset, appear to be incomplete, missing the original hypothesis. This seems to be a common issue across other datasets as well. Could you please provide the complete datasets, especially for the 'list functions'? Best regards!

**Comment by linlu-qiu** [comment]
Hi, thank you for your interest! The datasets do not have original hypotheses. The initial hypotheses are also proposed by LMs.

**Comment by gsoykan** [comment]
Thank you for your response, @linlu-qiu. I appreciate your prompt attention to my inquiry.

Regarding the "List Functions" dataset in the [thesis of Rule (2020) - The child as hacker](https://joshrule.com/files/rule2020child.pdf), I did come across the data embedded in the PDF as text format. However, it appears that only a portion (maybe it is the whole dataset, not sure) of the dataset (approximately 250 entries) is available in this format. To provide further context, I'm including a snapshot below.

![image](https://github.com/linlu-qiu/lm-inductive-reasoning/assets/11638870/bfde04a3-9719-4695-80e8-8b48c1c8b115)

If the "List Functions" dataset is not sourced from this PDF, could you kindly clarify the origin of the dataset and how it was obtained? Your insights would greatly assist me in my research.

Best regards,

**Comment by linlu-qiu** [comment]
Hi @gsoykan, the List Functions dataset is original from [here](https://github.com/joshrule/list_function_250/tree/main). It's also used in [BigBench](https://github.com/google/BIG-bench/tree/6436ed17f979b138463224421f8e8977b89076ed/bigbench/benchmark_tasks/list_functions). You can find the original description and human performance [here](https://github.com/google/BIG-bench/tree/main/bigbench/benchmark_tasks/list_functions#appendix-human-baseline-summary).

**Comment by gsoykan** [comment]
Thank you so much!
